#!/bin/bash
# INSTALL PHPLDAPADMIN SAS VIYA SERVER
# Este ainda não é um script para automatizar instalação, 
# apenas Step para montagem posterior no ambiente

# DOCUMENTACAO
# http://phpldapadmin.sourceforge.net/wiki/index.php/Main_Page

sudo yum install epel-release -y
sudo yum install phpldapadmin -y #install phpldapadmin
	
sudo vi /etc/httpd/conf.d/phpldapadmin.conf
    #Require local       #comment
    Require all granted  #adicione line
	:wq
	
sudo vi /etc/phpldapadmin/config.php #set config
		- $servers->setValue('server','name','SAS Viya LDAP Admin');
		- $servers->setValue('server','host','IP-SERVER-LDAPSASVIYA-OR-FQDN');
		- $servers->setValue('server','base',array('dc=ldapviya,dc=com'));
		- $servers->setValue('login','attr','dn');
		- $ //servers->setValue('login','attr','uid'); #Comment line
 	        - $ //servers->setValue('login','bind_id','cn=admin,dc=ldapviya,dc=com'); #Comment Line
		- $config->custom->appearance['hide_template_warning'] = true;   
		- $servers->setValue('server','tls',false);
sudo service httpd restart   #restart webserver

# Acesse a aplicação
http://<SERVER>/ldapadmin
